export interface AgendaItem {
  id?: string; // Auto-generated by Firestore if stored in a separate collection
  eventId: string; // ID of the event this agenda item belongs to
  startTime: Date; // Start time of the session/activity
  endTime: Date; // End time of the session/activity
  title: string;
  description?: string;
  speakerIds?: string[]; // IDs of speakers for this session
  location?: string; // Specific room or virtual breakout room
  type: 'keynote' | 'session' | 'workshop' | 'break' | 'networking';
  // Add other agenda-specific fields here
} 