export interface Attendee {
  id?: string; // Auto-generated by Firestore
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  company?: string;
  jobTitle?: string;
  registrationDate: Date;
  ticketType: 'regular' | 'vip' | 'early-bird';
  status: 'registered' | 'checked-in' | 'cancelled';
  dietaryRestrictions?: string[];
  specialRequirements?: string;
  eventId: string;
  updatedAt?: Date;
} 