export interface Event {
  id?: string; // Auto-generated by Firestore
  name: string;
  description: string;
  date: Date; // Start date and time of the event
  endDate?: Date; // Optional: End date and time of the event
  platform: string; // e.g., "Zoom", "Google Meet", "Custom Platform"
  url?: string; // URL to join the virtual event
  isOnline: boolean; // True if it's a virtual/online event
  location?: string; // Physical location if it's a hybrid or in-person event component
  tags?: string[]; // For categorization, e.g., ["tech", "conference", "workshop"]
  organizer: string; // Name or ID of the event organizer/host
  speakerIds?: string[]; // Array of Speaker IDs
  agendaItemIds?: string[]; // Array of AgendaItem IDs (implies agenda items stored separately)
  maxAttendees?: number;
  registeredAttendeesCount?: number; // Consider storing actual list elsewhere if large
  sponsorIds?: string[]; // Array of Sponsor IDs
  status: 'upcoming' | 'live' | 'past' | 'cancelled' | 'postponed';
  bannerImage?: string; // URL for the event banner
  logoImage?: string; // URL for the event logo
  isPrivate?: boolean; // True if the event is invite-only or not publicly listed
  entryFee?: number; // 0 for free events
  currency?: string; // e.g., "USD", "EUR", "INR"
  contactEmail?: string; // Email for event inquiries
  additionalInfo?: string; // Any other relevant information
  createdAt?: Date; // Timestamp of event creation
  updatedAt?: Date; // Timestamp of last event update
} 