export interface Speaker {
  id?: string; // Auto-generated by Firestore if stored in a separate collection
  name: string;
  bio?: string;
  avatarUrl?: string;
  email?: string;
  linkedIn?: string;
  twitter?: string;
  company?: string;
  jobTitle?: string;
  // Add other speaker-specific fields here
} 