export interface Sponsor {
  id?: string; // Auto-generated by Firestore if stored in a separate collection
  name: string;
  logoUrl?: string;
  website?: string;
  tier: 'platinum' | 'gold' | 'silver' | 'bronze' | 'community'; // Sponsorship level
  description?: string;
  contactEmail?: string;
  // Add other sponsor-specific fields here
} 